In [1]:
import os
import pandas as pd
import pandas_ta as ta
from vnstock import Quote
from ollama import Client
from dotenv import load_dotenv

In [2]:
ticker = "VCB"

In [3]:
quote = Quote(symbol=ticker, source="VCI")

In [4]:
df = quote.history(length="3M", interval="1D")
df

         time  open  high   low  close    volume
0  2026-01-09  65.4  68.0  65.4   68.0  32481400
1  2026-01-12  69.9  72.7  69.6   72.7  21973100
2  2026-01-13  74.3  76.0  71.8   74.0  28198200
3  2026-01-14  73.1  78.8  73.1   76.0  21213600
4  2026-01-15  74.0  74.9  71.9   71.9  23227200
..        ...   ...   ...   ...    ...       ...
61 2026-04-13  59.5  59.5  59.0   59.2   5088700
62 2026-04-14  59.7  59.8  59.1   59.3   5548100
63 2026-04-15  59.7  60.5  59.6   59.9   8919600
64 2026-04-16  60.0  60.1  59.3   59.4   4174500
65 2026-04-17  59.4  59.9  59.4   59.5   4257800

[66 rows x 6 columns]

In [5]:
df['RSI'] = ta.rsi(close=df['close'], length=14) # type: ignore
df

         time  open  high   low  close    volume         RSI
0  2026-01-09  65.4  68.0  65.4   68.0  32481400         NaN
1  2026-01-12  69.9  72.7  69.6   72.7  21973100  100.000000
2  2026-01-13  74.3  76.0  71.8   74.0  28198200  100.000000
3  2026-01-14  73.1  78.8  73.1   76.0  21213600  100.000000
4  2026-01-15  74.0  74.9  71.9   71.9  23227200   93.139364
..        ...   ...   ...   ...    ...       ...         ...
61 2026-04-13  59.5  59.5  59.0   59.2   5088700   50.094647
62 2026-04-14  59.7  59.8  59.1   59.3   5548100   50.542239
63 2026-04-15  59.7  60.5  59.6   59.9   8919600   53.251431
64 2026-04-16  60.0  60.1  59.3   59.4   4174500   50.756271
65 2026-04-17  59.4  59.9  59.4   59.5   4257800   51.248278

[66 rows x 7 columns]

In [6]:
macd = ta.macd(close=df['close'], fast=12, slow=26, signal=9) # type: ignore
macd

    MACD_12_26_9  MACDh_12_26_9  MACDs_12_26_9
0            NaN            NaN            NaN
1            NaN            NaN            NaN
2            NaN            NaN            NaN
3            NaN            NaN            NaN
4            NaN            NaN            NaN
..           ...            ...            ...
61     -0.868749       0.486024      -1.354773
62     -0.779926       0.459877      -1.239803
63     -0.653584       0.468975      -1.122560
64     -0.587036       0.428419      -1.015455
65     -0.520230       0.396180      -0.916410

[66 rows x 3 columns]

In [7]:
df = df.join(macd)
df

,time,open,high,low,close,volume,RSI,MACD_12_26_9,MACDh_12_26_9,MACDs_12_26_9
0,2026-01-09,65.4,68.0,65.4,68.0,32481400,NaN,NaN,NaN,NaN
1,2026-01-12,69.9,72.7,69.6,72.7,21973100,100.000000,NaN,NaN,NaN
2,2026-01-13,74.3,76.0,71.8,74.0,28198200,100.000000,NaN,NaN,NaN
3,2026-01-14,73.1,78.8,73.1,76.0,21213600,100.000000,NaN,NaN,NaN
4,2026-01-15,74.0,74.9,71.9,71.9,23227200,93.139364,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
61,2026-04-13,59.5,59.5,59.0,59.2,5088700,50.094647,-0.868749,0.486024,-1.354773
62,2026-04-14,59.7,59.8,59.1,59.3,5548100,50.542239,-0.779926,0.459877,-1.239803
63,2026-04-15,59.7,60.5,59.6,59.9,8919600,53.251431,-0.653584,0.468975,-1.122560
64,2026-04-16,60.0,60.1,59.3,59.4,4174500,50.756271,-0.587036,0.428419,-1.015455
65,2026-04-17,59.4,59.9,59.4,59.5,4257800,51.248278,-0.520230,0.396180,-0.916410

In [8]:
bbands = ta.bbands(close=df['close'], length=20, std=2) # type: ignore
bbands

,BBL_20_2.0_2.0,BBM_20_2.0_2.0,BBU_20_2.0_2.0,BBB_20_2.0_2.0,BBP_20_2.0_2.0
0,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...
61,56.836515,58.765,60.693485,6.563378,0.612783
62,56.935700,58.705,60.474300,6.027765,0.668146
63,57.017005,58.675,60.332995,5.651453,0.869422
64,57.045195,58.655,60.264805,5.489065,0.731394
65,57.108954,58.730,60.351046,5.520333,0.737501

In [9]:
df = df.join(bbands)
df

,time,open,high,low,close,volume,RSI,MACD_12_26_9,MACDh_12_26_9,MACDs_12_26_9,BBL_20_2.0_2.0,BBM_20_2.0_2.0,BBU_20_2.0_2.0,BBB_20_2.0_2.0,BBP_20_2.0_2.0
0,2026-01-09,65.4,68.0,65.4,68.0,32481400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-01-12,69.9,72.7,69.6,72.7,21973100,100.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-01-13,74.3,76.0,71.8,74.0,28198200,100.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-01-14,73.1,78.8,73.1,76.0,21213600,100.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-01-15,74.0,74.9,71.9,71.9,23227200,93.139364,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,2026-04-13,59.5,59.5,59.0,59.2,5088700,50.094647,-0.868749,0.486024,-1.354773,56.836515,58.765,60.693485,6.563378,0.612783
62,2026-04-14,59.7,59.8,59.1,59.3,5548100,50.542239,-0.779926,0.459877,-1.239803,56.935700,58.705,60.474300,6.027765,0.668146
63,2026-04-15,59.7,60.5,59.6,59.9,8919600,53.251431,-0.653584,0.468975,-1.122560,57.017005,58.675,60.332995,5.651453,0.869422
64,2026-04-16,60.0,60.1,59.3,59.4,4174500,50.756271,-0.587036,0.428419,-1.015455,57.045195,58.655,60.264805,5.489065,0.731394
65,2026-04-17,59.4,59.9,59.4,59.5,4257800,51.248278,-0.520230,0.396180,-0.916410,57.108954,58.730,60.351046,5.520333,0.737501

In [10]:
cols_to_round = {
    'open': 1, 'high': 1, 'low': 1, 'close': 1,
    'RSI': 2, 'MACD_12_26_9': 2, 'MACDh_12_26_9': 2, 'MACDs_12_26_9': 2,
    'BBL_20_2.0_2.0': 2, 'BBM_20_2.0_2.0': 2, 'BBU_20_2.0_2.0': 2,
    'BBB_20_2.0_2.0': 2, 'BBP_20_2.0_2.0': 2
}

In [11]:
df = df.tail(15).round(cols_to_round).fillna("N/A")
df

,time,open,high,low,close,volume,RSI,MACD_12_26_9,MACDh_12_26_9,MACDs_12_26_9,BBL_20_2.0_2.0,BBM_20_2.0_2.0,BBU_20_2.0_2.0,BBB_20_2.0_2.0,BBP_20_2.0_2.0
51,2026-03-30,57.9,58.5,57.8,58.0,5546000,44.37,-2.06,0.25,-2.31,56.26,59.60,62.95,11.24,0.26
52,2026-03-31,58.2,58.9,58.0,58.1,5481100,44.78,-1.97,0.27,-2.25,56.15,59.43,62.71,11.02,0.30
53,2026-04-01,58.9,59.2,58.5,59.0,8254700,48.45,-1.81,0.35,-2.16,56.42,59.23,62.04,9.50,0.46
54,2026-04-02,58.7,58.8,58.1,58.2,5664500,45.55,-1.73,0.34,-2.07,56.63,59.02,61.40,8.09,0.33
55,2026-04-03,58.3,58.5,57.7,57.7,5919600,43.79,-1.69,0.31,-2.00,56.70,58.82,60.94,7.21,0.24
56,2026-04-06,57.8,58.2,57.7,58.0,4303300,45.16,-1.61,0.31,-1.92,56.82,58.86,60.89,6.92,0.29
57,2026-04-07,58.0,58.3,57.7,58.0,3889100,45.16,-1.53,0.31,-1.84,56.80,58.74,60.67,6.58,0.31
58,2026-04-08,59.2,60.3,58.8,60.2,13743100,54.59,-1.27,0.45,-1.73,56.83,58.72,60.62,6.46,0.89
59,2026-04-09,60.0,60.1,59.3,59.4,6217700,51.15,-1.12,0.48,-1.61,56.85,58.70,60.56,6.33,0.69
60,2026-04-10,59.6,61.0,59.6,59.8,7655400,52.75,-0.96,0.52,-1.48,56.83,58.74,60.66,6.53,0.78
61,2026-04-13,59.5,59.5,59.0,59.2,5088700,50.09,-0.87,0.49,-1.35,56.84,58.76,60.69,6.56,0.61
62,2026-04-14,59.7,59.8,59.1,59.3,5548100,50.54,-0.78,0.46,-1.24,56.94,58.70,60.47,6.03,0.67
63,2026-04-15,59.7,60.5,59.6,59.9,8919600,53.25,-0.65,0.47,-1.12,57.02,58.67,60.33,5.65,0.87
64,2026-04-16,60.0,60.1,59.3,59.4,4174500,50.76,-0.59,0.43,-1.02,57.05,58.65,60.26,5.49,0.73
65,2026-04-17,59.4,59.9,59.4,59.5,4257800,51.25,-0.52,0.40,-0.92,57.11,58.73,60.35,5.52,0.74

In [12]:
markdown_table = df.to_markdown(index=False)
print(markdown_table)

| time                |   open |   high |   low |   close |   volume |   RSI |   MACD_12_26_9 |   MACDh_12_26_9 |   MACDs_12_26_9 |   BBL_20_2.0_2.0 |   BBM_20_2.0_2.0 |   BBU_20_2.0_2.0 |   BBB_20_2.0_2.0 |   BBP_20_2.0_2.0 |
|:--------------------|-------:|-------:|------:|--------:|---------:|------:|---------------:|----------------:|----------------:|-----------------:|-----------------:|-----------------:|-----------------:|-----------------:|
| 2026-03-30 00:00:00 |   57.9 |   58.5 |  57.8 |    58   |  5546000 | 44.37 |          -2.06 |            0.25 |           -2.31 |            56.26 |            59.6  |            62.95 |            11.24 |             0.26 |
| 2026-03-31 00:00:00 |   58.2 |   58.9 |  58   |    58.1 |  5481100 | 44.78 |          -1.97 |            0.27 |           -2.25 |            56.15 |            59.43 |            62.71 |            11.02 |             0.3  |
| 2026-04-01 00:00:00 |   58.9 |   59.2 |  58.5 |    59   |  8254700 | 48.45 |          -1.81 |            0.35 |           -2.16 |            56.42 |            59.23 |            62.04 |             9.5  |             0.46 |
| 2026-04-02 00:00:00 |   58.7 |   58.8 |  58.1 |    58.2 |  5664500 | 45.55 |          -1.73 |            0.34 |           -2.07 |            56.63 |            59.02 |            61.4  |             8.09 |             0.33 |
| 2026-04-03 00:00:00 |   58.3 |   58.5 |  57.7 |    57.7 |  5919600 | 43.79 |          -1.69 |            0.31 |           -2    |            56.7  |            58.82 |            60.94 |             7.21 |             0.24 |
| 2026-04-06 00:00:00 |   57.8 |   58.2 |  57.7 |    58   |  4303300 | 45.16 |          -1.61 |            0.31 |           -1.92 |            56.82 |            58.86 |            60.89 |             6.92 |             0.29 |
| 2026-04-07 00:00:00 |   58   |   58.3 |  57.7 |    58   |  3889100 | 45.16 |          -1.53 |            0.31 |           -1.84 |            56.8  |            58.74 |            60.67 |             6.58 |             0.31 |
| 2026-04-08 00:00:00 |   59.2 |   60.3 |  58.8 |    60.2 | 13743100 | 54.59 |          -1.27 |            0.45 |           -1.73 |            56.83 |            58.72 |            60.62 |             6.46 |             0.89 |
| 2026-04-09 00:00:00 |   60   |   60.1 |  59.3 |    59.4 |  6217700 | 51.15 |          -1.12 |            0.48 |           -1.61 |            56.85 |            58.7  |            60.56 |             6.33 |             0.69 |
| 2026-04-10 00:00:00 |   59.6 |   61   |  59.6 |    59.8 |  7655400 | 52.75 |          -0.96 |            0.52 |           -1.48 |            56.83 |            58.74 |            60.66 |             6.53 |             0.78 |
| 2026-04-13 00:00:00 |   59.5 |   59.5 |  59   |    59.2 |  5088700 | 50.09 |          -0.87 |            0.49 |           -1.35 |            56.84 |            58.76 |            60.69 |             6.56 |             0.61 |
| 2026-04-14 00:00:00 |   59.7 |   59.8 |  59.1 |    59.3 |  5548100 | 50.54 |          -0.78 |            0.46 |           -1.24 |            56.94 |            58.7  |            60.47 |             6.03 |             0.67 |
| 2026-04-15 00:00:00 |   59.7 |   60.5 |  59.6 |    59.9 |  8919600 | 53.25 |          -0.65 |            0.47 |           -1.12 |            57.02 |            58.67 |            60.33 |             5.65 |             0.87 |
| 2026-04-16 00:00:00 |   60   |   60.1 |  59.3 |    59.4 |  4174500 | 50.76 |          -0.59 |            0.43 |           -1.02 |            57.05 |            58.65 |            60.26 |             5.49 |             0.73 |
| 2026-04-17 00:00:00 |   59.4 |   59.9 |  59.4 |    59.5 |  4257800 | 51.25 |          -0.52 |            0.4  |           -0.92 |            57.11 |            58.73 |            60.35 |             5.52 |             0.74 |

In [13]:
SYSTEM_PROMPT = """
Bạn là một Chuyên gia Phân tích Kỹ thuật (Technical Analyst) lão luyện tại thị trường chứng khoán Việt Nam.
Nhiệm vụ của bạn là đọc bảng dữ liệu lịch sử giá, các chỉ báo kỹ thuật và đưa ra KHUYẾN NGHỊ GIAO DỊCH CỤ THỂ.

Mục tiêu phân tích:
1. Đánh giá Xu hướng & Động lượng: Dựa vào sự hội tụ/phân kỳ của MACD và sức mạnh của RSI.
2. Đánh giá Biến động & Vị thế giá: Dựa vào Bollinger Bands (BBL, BBM, BBU, độ rộng BBB, vị trí BBP).
3. Xác định Vùng Giá (Price Action): Quan sát mức giá Cao nhất (high), Thấp nhất (low) và Đóng cửa (close) để tìm Hỗ trợ (Support) và Kháng cự (Resistance) gần nhất.

Ràng buộc nghiêm ngặt:
- Báo cáo phải có tính thực chiến: Bắt buộc nêu rõ mức giá cụ thể để Cắt lỗ (Stop-loss) và Chốt lời (Take-profit) dựa trên dữ liệu bảng.
- Tuyệt đối chỉ sử dụng dữ liệu được cung cấp trong bảng Markdown, không bịa đặt số liệu.
- Tuyệt đối KHÔNG phân tích các yếu tố vĩ mô hay tin tức cơ bản (đó là việc của phòng ban khác), chỉ tập trung vào hành vi giá và xung lượng.
- Giọng văn chuyên nghiệp, quyết đoán, đi thẳng vào vấn đề.
"""

In [14]:
user_prompt = f"""
Thực hiện phân tích kỹ thuật và đưa ra kế hoạch giao dịch cho mã cổ phiếu: {ticker}
Dưới đây là dữ liệu 15 phiên gần nhất:

{markdown_table}

Hãy trình bày báo cáo theo cấu trúc Markdown sau:

### I. Đánh giá Trạng thái Kỹ thuật
- **Xu hướng & Động lượng:** (Phân tích ngắn gọn MACD và RSI)
- **Biến động giá:** (Phân tích Bollinger Bands, hiện tượng thắt nút cổ chai hoặc giá bám dải)

### II. Các mốc giá quan trọng
- **Hỗ trợ gần nhất (Support):** (Tìm mức giá thấp hoặc dải BBL gần nhất để làm điểm tựa)
- **Kháng cự gần nhất (Resistance):** (Tìm đỉnh giá cao hoặc dải BBU gần nhất)

### III. Khuyến nghị Giao dịch Thực chiến
- **Hành động:** (MUA / BÁN / NẮM GIỮ / QUAN SÁT)
- **Vùng giá hành động:** (Ví dụ: Mua gom quanh vùng giá X - Y)
- **Mục tiêu chốt lời (Target):** (Mức giá Z - Giải thích ngắn gọn)
- **Ngưỡng cắt lỗ (Stop-loss):** (Mức giá W - Phá vỡ mức này thì xu hướng hỏng)
"""

In [15]:
messages = [
    {'role': 'system', 'content': SYSTEM_PROMPT},
    {'role': 'user', 'content': user_prompt},
]

In [16]:
load_dotenv()

True

In [17]:
HOST = os.getenv("OLLAMA_HOST")
API_KEY = os.getenv("OLLAMA_API_KEY")

In [18]:
client = Client(
    host=HOST,
    headers={'Authorization': f'Bearer {API_KEY}'}
)

In [19]:
MODEL = os.getenv("OLLAMA_MODEL")

In [20]:
if MODEL is None:
    raise ValueError("OLLAMA_MODEL environment variable is not set")

response = client.chat(
    model=MODEL,
    messages=messages,
)

In [21]:
print(response['message']['content'])

### I. Đánh giá Trạng thái Kỹ thuật

- **Xu hướng & Động lượng:**
    - **MACD:** Đang trong pha hồi phục tích cực. Đường MACD (`-0.52`) liên tục hướng lên và thu hẹp khoảng cách với đường Signal, trong khi MACD Histogram (`MACDh`) duy trì giá trị dương (`0.4`) xuyên suốt 15 phiên gần nhất. Điều này cho thấy áp lực bán đã bị đẩy lùi và phe mua đang kiểm soát xung lực ngắn hạn.
    - **RSI:** Dao động trong vùng 44 - 54, hiện tại ở mức `51.25`. RSI nằm trên mức 50 cho thấy trạng thái cân bằng nghiêng về phía tích cực, không có dấu hiệu quá mua hay quá bán, tạo dư địa cho giá tăng tiếp.

- **Biến động giá:**
    - **Bollinger Bands:** Độ rộng dải băng (`BBB`) đang thu hẹp dần (từ `11.24` xuống còn `5.52`), cho thấy hiện tượng "thắt nút cổ chai" đang diễn ra. Giá đóng cửa (`59.5`) hiện nằm trên đường trung bình `BBM` (`58.73`) và đang tiệm cận dải trên `BBU` (`60.35`).
    - **Vị thế giá:** Chỉ số `BBP` ở mức `0.74` cho thấy giá đang áp sát vùng kháng cự trên của dải Bollinger, chuẩn bị cho một pha bứt phá (breakout) hoặc điều chỉnh nhẹ.

### II. Các mốc giá quan trọng

- **Hỗ trợ gần nhất (Support):** **58.7 - 59.0**. (Vùng giao thoa giữa đường BBM `58.73` và mức giá thấp nhất của các phiên điều chỉnh gần đây).
- **Kháng cự gần nhất (Resistance):** **60.3 - 61.0**. (Đỉnh ngắn hạn ngày 10/04 là `61.0` và dải BBU hiện tại là `60.35`).

### III. Khuyến nghị Giao dịch Thực chiến

- **Hành động:** **MUA GOM / NẮM GIỮ**
- **Vùng giá hành động:** Mua gom trong vùng **59.2 - 59.5**.
- **Mục tiêu chốt lời (Target):** **61.0 - 62.0**.
    - *Giải thích:* Kỳ vọng giá bứt phá khỏi vùng thắt nút cổ chai của Bollinger Bands và quay lại kiểm tra đỉnh cao nhất trong 15 phiên (`61.0`).
- **Ngưỡng cắt lỗ (Stop-loss):** **58.0**.
    - *Giải thích:* Nếu giá đóng cửa dưới `58.0`, cổ phiếu sẽ phá vỡ vùng hỗ trợ tâm lý và đường BBM, xác nhận xu hướng hồi phục thất bại.